name: Publish Dup-composer to PyPI.
on: push

jobs:
  publish:
    name: Build the package and publish to PyPI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install setuptools, wheel
        run: >-
          python -m pip
          install setuptools
          wheel --user
      - name: Build package
        run: >-
          python setup.py
          sdist bdist_wheel
      - name: Publish to Test PyPI
        if: ${{ ! startsWith(github.event.ref, 'refs/tags/v0') }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: startsWith(github.event.ref, 'refs/tags/v0')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          
