name: Publish Dup-composer to PyPI.
on:
  push:
    tags:
      - release*
jobs:
  publish:
    name: Build the package and publish to PyPI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install setuptools
        run: >-
          python -m pip
          install setuptools
          --user
      - name: Build package
        run: >-
          python setup.py
          sdist bdist_wheel
      - if: github.ref == 'refs/tags/release-test'
        name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy
      - if: github.ref == 'refs/tags/release'
        name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          
