#!/usr/bin/env python
import sys
import json
import os.path

def main():
    print("Duplicity dummy implementation executed.")
    outfile = 'tests/temp/dummy-out.json'
    cache = []
    if os.path.isfile(outfile):
        with open(outfile) as f:
            filecontent = f.read()
            if filecontent:
                cache = json.loads(filecontent)

    cache.append(sys.argv[1:])

    with open(outfile, 'w') as f:
        f.write(json.dumps(cache))

if __name__ == '__main__':
    main()
