#!/usr/bin/env python
import sys
import json
import os
import uuid


def filter_dup_env(env):
    """Filter Duplicity related environment variables.

    Keep only the environment variables, that are used
    by Duplicity.
    """
    duplicity_vars = ('AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'FTP_PASSWORD')
    filtered = {key: env[key] for key in duplicity_vars if key in env}
    return filtered


def main():
    if sys.argv[1] == '--version':
        print('duplicity 0.7.1')
        exit(0)
    print("Duplicity dummy implementation executed.")
    # Read the output file we need to write into
    outfile = os.environ['duplicity_mock_outfile']
    cache = {'args': [], 'envs': []}
    if os.path.isfile(outfile):
        with open(outfile) as f:
            filecontent = f.read()
            if filecontent:
                cache = json.loads(filecontent)

    cache['args'].append(sys.argv[1:])
    cache['envs'].append(filter_dup_env(os.environ))

    with open(outfile, 'w') as f:
        f.write(json.dumps(cache))


if __name__ == '__main__':
    main()
